# Generated by Django 5.0.6 on 2024-06-20 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="کد معرف",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_referral_code",
            field=models.CharField(
                default=uuid.UUID("35870825-6a93-4cfb-b5c0-71fb0f778d79"),
                max_length=128,
                null=True,
                unique=True,
                verbose_name="کد معرف کاربر",
            ),
        ),
    ]
